AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  This is a sample serverless application using Swift language.

Globals:
  Function:
    Timeout: 3
    Tracing: Active

Resources:
  BaseApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      MethodSettings:
        - LoggingLevel: INFO
          HttpMethod: "*"
          ResourcePath: "/*"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: Provided
      Runtime: provided
      CodeUri: './.build/lambda/HelloWorld/lambda.zip'
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref BaseApi

  GreetingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: Provided
      Runtime: provided
      CodeUri: '.build/lambda/Greeting/lambda.zip'
      Events:
        Greeting:
          Type: Api
          Properties:
            Path: /greeting
            Method: get
            RestApiId: !Ref BaseApi

Outputs:
  HelloWorldApiEndpoint:
    Description: 'API Gateway endpoint URL.'
    Value: !Sub 'https://${BaseApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello'
  HelloWorldFunction:
    Description: "HelloWorldFunction Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  GreetingApiEndpoint:
    Description: 'API Gateway endpoint URL.'
    Value: !Sub 'https://${BaseApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greeting'
  GreetingAFunction:
    Description: "HelloWorldFunction Lambda Function ARN"
    Value: !GetAtt GreetingFunction.Arn

